export default [
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "CEO",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "VP & Product Management",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "CTO & Head of Engineering",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "PR & Marketing",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Engineer",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Data Analyist",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Office Manager",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "User Acquisition Manager",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Marketing Associate",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Marketing",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "John",
    role: "Marketing Assistant Coordinator",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "Julia",
    role: "UX Researcher",
  },
  {
    liUrl: "https://www.linkedin.com/in/",
    className: "employee-img",
    firstName: "Rebecca",
    role: "Marketing",
  },
]
